import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import "./globals.css";
import NavbarMain from "@/components/Navbar/Navbar";
import { Providers } from "./_Nextui/provider";
import Footer from "@/components/Footer/Footer";
// done
const inter = DM_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <div className="  mx-auto  lg:px-0 ">
            <NavbarMain />
            {children}
            <Footer />
          </div>
        </Providers>
      </body>
    </html>
  );
}
