import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavbarMain from "@/components/Navbar/Navbar";
import { Providers } from "./Nextui/provider";

// done
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <div className="  mx-auto  lg:px-0">
            <NavbarMain />
            {children}
          </div>
        </Providers>
      </body>
    </html>
  );
}
